[package]
name = "vampc"
version = "0.1.0"
authors = ["Matan Lurey <matan@lurey.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
"cargo-watch" = "7.3.0"
